name: game_notion
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  get: ^4.6.6
  flutter_snake_navigationbar: ^0.6.1
  cloud_firestore: ^4.15.8
  dio: ^5.4.3+1
  animate_do: ^3.3.4
  flutter_typeahead: ^5.2.0
  loading_animation_widget: ^1.2.1
  flutter_svg: ^2.0.10+1
  easy_image_viewer: ^1.5.0
  fast_cached_network_image: ^1.2.9
  fast_ui_kit: ^1.0.16
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  msix: ^3.16.1
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
msix_config:
  display_name: Game Notion
  publisher_display_name: Game Notion
  identity_name: GameNotion
  msix_version: 1.0.0.0
  logo_path: assets\images\logo.png
